# Generated by Django 5.0.14 on 2026-05-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellidos')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('estado', models.CharField(choices=[('pendiente_verificacion', 'Pendiente de Verificación'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado'), ('autoexcluido', 'Autoexcluido')], default='pendiente_verificacion', max_length=25, verbose_name='estado')),
                ('fecha_exclusion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de autoexclusión')),
                ('fecha_fin_exclusion', models.DateTimeField(blank=True, null=True, verbose_name='fin de autoexclusión')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='DepositLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(decimal_places=4, default=500, max_digits=18, verbose_name='límite diario')),
                ('weekly_limit', models.DecimalField(decimal_places=4, default=2000, max_digits=18, verbose_name='límite semanal')),
                ('monthly_limit', models.DecimalField(decimal_places=4, default=5000, max_digits=18, verbose_name='límite mensual')),
                ('cooldown_hasta', models.DateTimeField(blank=True, null=True, verbose_name='cooldown hasta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_limit', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'límite de depósito',
                'verbose_name_plural': 'límites de depósito',
            },
        ),
    ]
