# Generated by Django 5.0.14 on 2026-05-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_excluded',
        ),
        migrations.AddField(
            model_name='depositlimit',
            name='cooldown_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cooldown hasta'),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('pendiente_verificacion', 'Pendiente de Verificación'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado'), ('autoexcluido', 'Autoexcluido')], default='pendiente_verificacion', max_length=25, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_exclusion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de autoexclusión'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_fin_exclusion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin de autoexclusión'),
        ),
    ]
