# Generated by Django 5.0.14 on 2026-05-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_excluded_depositlimit_cooldown_hasta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=9, unique=True, verbose_name='DNI'),
        ),
    ]
