# Generated by Django 5.0.14 on 2026-05-28 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(max_length=20, verbose_name='selección')),
                ('cuota_al_apostar', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cuota')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='monto')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('won', 'Ganada'), ('lost', 'Perdida'), ('cancelled', 'Cancelada'), ('cashed_out', 'Retirada')], default='pending', max_length=20, verbose_name='estado')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='events.event')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='events.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'apuesta',
                'verbose_name_plural': 'apuestas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComboBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='monto')),
                ('cuota_total', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cuota total')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('won', 'Ganada'), ('lost', 'Perdida'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='estado')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'apuesta combinada',
                'verbose_name_plural': 'apuestas combinadas',
            },
        ),
        migrations.CreateModel(
            name='ComboLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(max_length=20, verbose_name='selección')),
                ('cuota', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cuota')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='betting.combobet')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.market')),
            ],
            options={
                'verbose_name': 'pierna de combo',
                'verbose_name_plural': 'piernas de combo',
            },
        ),
    ]
