# Generated by Django 5.0.6 on 2026-05-28 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combobet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comboleg',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='betting.combobet'),
        ),
        migrations.AddField(
            model_name='comboleg',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
        migrations.AddField(
            model_name='comboleg',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.market'),
        ),
    ]
