# Generated by Django 5.0.6 on 2026-05-30 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255, verbose_name='motivo')),
                ('severidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20, verbose_name='severidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha de detección')),
                ('resuelto', models.BooleanField(default=False, verbose_name='resuelto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_fraude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'actividad sospechosa',
                'verbose_name_plural': 'actividades sospechosas',
                'ordering': ['-fecha'],
            },
        ),
    ]
