# Generated by Django 5.0.6 on 2026-05-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_suspiciousactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='combobet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
    ]
