# Generated by Django 5.0.6 on 2026-05-28 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=100, verbose_name='equipo local')),
                ('equipo_visitante', models.CharField(max_length=100, verbose_name='equipo visitante')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('estado', models.CharField(choices=[('scheduled', 'Programado'), ('live', 'En vivo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='scheduled', max_length=20, verbose_name='estado')),
                ('resultado', models.CharField(blank=True, choices=[('local', 'Local'), ('empate', 'Empate'), ('visita', 'Visita')], max_length=10, null=True, verbose_name='resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('one_x_two', '1X2'), ('over_under', 'Over/Under 2.5'), ('btts', 'Ambos Marcan (BTTS)'), ('asian_handicap', 'Hándicap Asiático')], default='one_x_two', max_length=20, verbose_name='tipo')),
                ('cuota_local', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cuota local')),
                ('cuota_empate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='cuota empate')),
                ('cuota_visitante', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cuota visitante')),
                ('margen', models.DecimalField(decimal_places=4, default=0.05, max_digits=6, verbose_name='margen')),
                ('estado', models.CharField(choices=[('open', 'Abierto'), ('suspended', 'Suspendido'), ('settled', 'Liquidado')], default='open', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='events.event')),
            ],
            options={
                'verbose_name': 'mercado',
                'verbose_name_plural': 'mercados',
            },
        ),
    ]
