# Generated by Django 5.0.14 on 2026-05-29 05:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='estado',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('live', 'En vivo'), ('suspendido', 'Suspendido'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='scheduled', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='market',
            name='margen',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=6, verbose_name='margen'),
        ),
    ]
