# Generated by Django 5.0.14 on 2026-05-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_estado_alter_market_margen'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categoria',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('basketball', 'Basketball'), ('tenis', 'Tenis'), ('esports', 'E-Sports'), ('boxeo', 'Boxeo')], default='futbol', max_length=20, verbose_name='categoría'),
        ),
    ]
