# Generated by Django 5.0.14 on 2026-05-28 06:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('wallet_usuario', 'Billetera de Usuario'), ('casa', 'Cuenta de la Casa'), ('apuestas_pendientes', 'Apuestas Pendientes'), ('bonos', 'Bonos Promocionales')], max_length=30, verbose_name='tipo')),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='saldo')),
                ('version', models.IntegerField(default=1, verbose_name='versión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='débito')),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='crédito')),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='saldo después')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.account')),
            ],
            options={
                'verbose_name': 'asiento contable',
                'verbose_name_plural': 'asientos contables',
                'ordering': ['created_at'],
            },
        ),
    ]
