# Generated by Django 5.0.14 on 2026-05-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='balance_after',
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='hash'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='hash anterior'),
        ),
    ]
